name: Build iOS IPA (KMP)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout koda
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Check Xcode
        run: |
          xcodebuild -version
          xcode-select -p

      - name: Build iOS Archive
        run: |
          xcodebuild \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$GITHUB_WORKSPACE/build/iosApp.xcarchive" \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Create unsigned IPA
        run: |
          mkdir -p build/Payload

          cp -R \
            build/iosApp.xcarchive/Products/Applications/*.app \
            build/Payload/

          cd build

          zip -r iosApp.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: build/iosApp.ipa